// Generated by scripts/generate-checkpoint-live-pilot-v02710.mjs.
// This active-development bank overrides only the first twelve Journey checkpoints.

export const ACTIVE_CHECKPOINT_BANK = 'v0.27.10-first-twelve'

export const FIRST_TWELVE_CHECKPOINT_BANK_V02710 = {
  "what-is-llm": {
    "questions": [
      {
        "id": "v0279-what-is-llm-q1",
        "question": "When an LLM answers a prompt by generating one token at a time, what is the model doing at each step?",
        "choices": [
          {
            "choiceId": "v0279-what-is-llm-q1-correct",
            "text": "It scores possible next tokens from the current context, selects one, appends it, and repeats."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-conscious-reader",
            "text": "It reads with conscious understanding, then writes the whole answer at once."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-hidden-search",
            "text": "It searches a hidden database and copies the best matching passage."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-weight-change",
            "text": "It changes its weights each time the user sends a new prompt."
          }
        ],
        "answer": "It scores possible next tokens from the current context, selects one, appends it, and repeats.",
        "correctChoiceId": "v0279-what-is-llm-q1-correct",
        "explain": "Good distinction. The model is using fixed learned weights and temporary context to make the next-token step.",
        "feedback": {
          "v0279-what-is-llm-q1-correct": "Good distinction. The model is using fixed learned weights and temporary context to make the next-token step.",
          "v0279-what-is-llm-q1-conscious-reader": "Not quite. That gives the model too much mind. Fluent behavior can happen without awareness.",
          "v0279-what-is-llm-q1-hidden-search": "This choice reveals a common mix-up. Search can be added around a model, but a plain LLM generates from context and learned weights.",
          "v0279-what-is-llm-q1-weight-change": "That would be true only if a separate training process updated weights. Ordinary inference usually leaves weights fixed."
        }
      },
      {
        "id": "v0279-what-is-llm-q2",
        "question": "An LLM gives a fluent explanation of a poem. What should a model-literate learner conclude?",
        "choices": [
          {
            "choiceId": "v0279-what-is-llm-q2-correct",
            "text": "It generated response tokens from context and learned patterns; fluency does not prove awareness."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-inner-awareness",
            "text": "It must have inner awareness because the explanation sounds human."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-hidden-source",
            "text": "It must have found a hidden perfect source and copied the interpretation."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-prompt-learning",
            "text": "The poem prompt permanently taught the base model a new skill."
          }
        ],
        "answer": "It generated response tokens from context and learned patterns; fluency does not prove awareness.",
        "correctChoiceId": "v0279-what-is-llm-q2-correct",
        "explain": "Insight strengthened. This is the fluent-behavior-without-awareness boundary Prompt Life wants learners to hold.",
        "feedback": {
          "v0279-what-is-llm-q2-correct": "Insight strengthened. This is the fluent-behavior-without-awareness boundary Prompt Life wants learners to hold.",
          "v0279-what-is-llm-q2-inner-awareness": "Not quite. That gives the model too much mind. Fluent behavior can happen without awareness.",
          "v0279-what-is-llm-q2-hidden-source": "Close, but this describes search or retrieval better than a plain LLM response. A fluent answer is not the same as cited evidence.",
          "v0279-what-is-llm-q2-prompt-learning": "That would require training. A normal prompt can shape temporary context without durably updating weights."
        }
      }
    ]
  },
  "where-llms-fit": {
    "questions": [
      {
        "id": "v0279-where-llms-fit-q1",
        "question": "A campus tool summarizes text with an LLM, while another creates images by denoising a noisy pattern. What does that show?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q1-correct",
            "text": "Generative AI is a family; LLMs and diffusion models are different branches."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-all-llms",
            "text": "All generative AI tools are LLMs because ChatGPT is generative AI."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-text-only-ai",
            "text": "The image tool is not AI unless it generates language tokens."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-ai-ml-same",
            "text": "AI and machine learning are the same label, so the branches do not matter."
          }
        ],
        "answer": "Generative AI is a family; LLMs and diffusion models are different branches.",
        "correctChoiceId": "v0279-where-llms-fit-q1-correct",
        "explain": "Good distinction. Generative AI is a family, and different branches can use different mechanisms.",
        "feedback": {
          "v0279-where-llms-fit-q1-correct": "Good distinction. Generative AI is a family, and different branches can use different mechanisms.",
          "v0279-where-llms-fit-q1-all-llms": "Not quite. An LLM is one kind of generative AI, not the whole category.",
          "v0279-where-llms-fit-q1-text-only-ai": "Close, but image models can be AI without using the LLM text-token loop.",
          "v0279-where-llms-fit-q1-ai-ml-same": "This choice collapses useful categories. Machine learning is a major branch inside the broader AI field."
        }
      },
      {
        "id": "v0279-where-llms-fit-q2",
        "question": "When people say an LLM sits inside the broader AI family, which category map is most useful?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q2-correct",
            "text": "AI is broad; machine learning learns from data; deep learning uses layers; generative AI creates outputs; LLMs focus on language/code."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-all-ai-llm",
            "text": "AI means LLM; machine learning, deep learning, and generative AI are just extra names."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-rules-learned-same",
            "text": "Rule-based AI, machine learning, and LLMs all work by following the same written rules."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-diffusion-same-loop",
            "text": "Diffusion models, LLMs, and search engines all use the same language-token loop."
          }
        ],
        "answer": "AI is broad; machine learning learns from data; deep learning uses layers; generative AI creates outputs; LLMs focus on language/code.",
        "correctChoiceId": "v0279-where-llms-fit-q2-correct",
        "explain": "Insight strengthened. The map keeps overlapping terms useful without making them interchangeable.",
        "feedback": {
          "v0279-where-llms-fit-q2-correct": "Insight strengthened. The map keeps overlapping terms useful without making them interchangeable.",
          "v0279-where-llms-fit-q2-all-ai-llm": "Not quite. LLMs are an important branch, not the root of the AI tree.",
          "v0279-where-llms-fit-q2-rules-learned-same": "Close, but rule-based systems rely on explicit rules while learned models use patterns shaped from data.",
          "v0279-where-llms-fit-q2-diffusion-same-loop": "This choice reveals a common mix-up. Diffusion often denoises patterns; LLM text generation usually appends response tokens."
        }
      },
      {
        "id": "v0279-where-llms-fit-q3",
        "question": "A chatbot product includes an LLM, a search tool, safety filters, and a user interface. What is the LLM?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q3-correct",
            "text": "The language-generating model inside the larger product."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-whole-app",
            "text": "The whole app, including every tool and button."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-safety-policy",
            "text": "The safety policy that blocks some outputs."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-search-index",
            "text": "The database or search index the app may call."
          }
        ],
        "answer": "The language-generating model inside the larger product.",
        "correctChoiceId": "v0279-where-llms-fit-q3-correct",
        "explain": "Good distinction. A product may wrap an LLM with tools, policies, and interface pieces.",
        "feedback": {
          "v0279-where-llms-fit-q3-correct": "Good distinction. A product may wrap an LLM with tools, policies, and interface pieces.",
          "v0279-where-llms-fit-q3-whole-app": "Not quite. The product can include an LLM, but the LLM is not every surrounding tool and screen.",
          "v0279-where-llms-fit-q3-safety-policy": "Close, but a safety policy shapes behavior around the model; it is not the language model itself.",
          "v0279-where-llms-fit-q3-search-index": "This describes a retrieval or search component. The LLM generates language from context and learned weights."
        }
      }
    ]
  },
  "history": {
    "questions": [
      {
        "id": "v0279-history-q1",
        "question": "If a system solves a task only by following hand-written if-then rules, how is it different from an LLM?",
        "choices": [
          {
            "choiceId": "v0279-history-q1-correct",
            "text": "The rule-based system applies explicit rules; an LLM’s fluency mostly comes from learned weights shaped by examples."
          },
          {
            "choiceId": "v0279-history-q1-loss-every-task",
            "text": "The rule-based system measures loss and updates weights after every task."
          },
          {
            "choiceId": "v0279-history-q1-conscious-llm",
            "text": "The LLM has conscious reasoning, while the rule-based system has none."
          },
          {
            "choiceId": "v0279-history-q1-all-rules",
            "text": "There is no difference; both systems are just written rulebooks."
          }
        ],
        "answer": "The rule-based system applies explicit rules; an LLM’s fluency mostly comes from learned weights shaped by examples.",
        "correctChoiceId": "v0279-history-q1-correct",
        "explain": "Good distinction. LLMs mostly belong to the learned-patterns tradition, even when products around them use rules.",
        "feedback": {
          "v0279-history-q1-correct": "Good distinction. LLMs mostly belong to the learned-patterns tradition, even when products around them use rules.",
          "v0279-history-q1-loss-every-task": "Not quite. Loss and weight updates belong to training learned models, not to a pure if-then rule system.",
          "v0279-history-q1-conscious-llm": "That gives the LLM too much mind. The key boundary here is learned weights versus explicit rules.",
          "v0279-history-q1-all-rules": "Close, but LLM behavior is not mainly written as explicit if-then rules; it is shaped by training."
        }
      },
      {
        "id": "v0279-history-q2",
        "question": "During deep-learning training, why does the system measure loss?",
        "choices": [
          {
            "choiceId": "v0279-history-q2-correct",
            "text": "Loss measures prediction error so an optimizer can adjust weights."
          },
          {
            "choiceId": "v0279-history-q2-moral-good",
            "text": "Loss tells the model whether a generated answer is morally good."
          },
          {
            "choiceId": "v0279-history-q2-confidence-score",
            "text": "Loss is the model’s confidence score for the next token during generation."
          },
          {
            "choiceId": "v0279-history-q2-final-answer",
            "text": "Loss writes the final answer after the model has finished thinking."
          }
        ],
        "answer": "Loss measures prediction error so an optimizer can adjust weights.",
        "correctChoiceId": "v0279-history-q2-correct",
        "explain": "Insight strengthened. Loss is the numerical training signal, not a feeling or truth meter.",
        "feedback": {
          "v0279-history-q2-correct": "Insight strengthened. Loss is the numerical training signal, not a feeling or truth meter.",
          "v0279-history-q2-moral-good": "Not quite. Loss is a numerical error signal; alignment and policy questions need additional methods.",
          "v0279-history-q2-confidence-score": "Close, but confidence or probability shapes generation. Loss measures training error so weights can be adjusted.",
          "v0279-history-q2-final-answer": "Not quite. Loss is used during training; it is not the model writing a response."
        }
      },
      {
        "id": "v0279-history-q3",
        "question": "A university AI app uses an LLM plus policy filters, retrieval, and hand-written rules. What should a model-literate user conclude?",
        "choices": [
          {
            "choiceId": "v0279-history-q3-correct",
            "text": "Modern AI products can combine learned models, rules, tools, and policies; the LLM inside is still a learned-pattern model."
          },
          {
            "choiceId": "v0279-history-q3-no-learning-if-rules",
            "text": "Any rule in the app means the LLM is no longer trained from data."
          },
          {
            "choiceId": "v0279-history-q3-conscious-product",
            "text": "Any fluent answer means the app is consciously reasoning."
          },
          {
            "choiceId": "v0279-history-q3-permanent-finetune",
            "text": "Retrieval or filters permanently fine-tune the model on every use."
          }
        ],
        "answer": "Modern AI products can combine learned models, rules, tools, and policies; the LLM inside is still a learned-pattern model.",
        "correctChoiceId": "v0279-history-q3-correct",
        "explain": "Good distinction. The product can be hybrid even when the LLM itself is learned from data.",
        "feedback": {
          "v0279-history-q3-correct": "Good distinction. The product can be hybrid even when the LLM itself is learned from data.",
          "v0279-history-q3-no-learning-if-rules": "Not quite. Rules can wrap or guide a learned model without erasing the learned weights inside it.",
          "v0279-history-q3-conscious-product": "That gives the model too much mind. The app can combine tools and still lack conscious understanding.",
          "v0279-history-q3-permanent-finetune": "Close, but retrieval and filters can shape the current response without durably changing model weights."
        }
      }
    ]
  },
  "training": {
    "questions": [
      {
        "id": "v0279-training-q1",
        "question": "During training, the model predicts a target token and gets it wrong. What makes that moment learning rather than ordinary inference?",
        "choices": [
          {
            "choiceId": "v0279-training-q1-correct",
            "text": "The training process uses the loss signal to update weights."
          },
          {
            "choiceId": "v0279-training-q1-append-response",
            "text": "The model appends the mistaken token to a normal live response."
          },
          {
            "choiceId": "v0279-training-q1-durable-memory",
            "text": "The prompt becomes durable memory stored inside the model’s weights."
          },
          {
            "choiceId": "v0279-training-q1-likelihood-truth",
            "text": "The model treats the most likely answer as automatically true."
          }
        ],
        "answer": "The training process uses the loss signal to update weights.",
        "correctChoiceId": "v0279-training-q1-correct",
        "explain": "Good distinction. The durable weight update is what makes this training.",
        "feedback": {
          "v0279-training-q1-correct": "Good distinction. The durable weight update is what makes this training.",
          "v0279-training-q1-append-response": "Not quite. Appending a response token is inference behavior; training uses loss to change weights.",
          "v0279-training-q1-durable-memory": "This choice reveals a common mix-up. Context can shape the current chat without becoming a weight update.",
          "v0279-training-q1-likelihood-truth": "Not quite. Likelihood is not truth, and this training moment matters because loss can drive a weight update."
        }
      },
      {
        "id": "v0279-training-q2",
        "question": "A student asks a chatbot one question during ordinary use. Which statement is usually true?",
        "choices": [
          {
            "choiceId": "v0279-training-q2-correct",
            "text": "The model uses fixed weights and temporary context; the chat usually does not rewrite the weights."
          },
          {
            "choiceId": "v0279-training-q2-permanent-update",
            "text": "The chat permanently updates the base model’s weights."
          },
          {
            "choiceId": "v0279-training-q2-durable-memory",
            "text": "The model stores the prompt as durable memory inside its weights."
          },
          {
            "choiceId": "v0279-training-q2-optimizer-after-response",
            "text": "The optimizer trains the model after every response."
          }
        ],
        "answer": "The model uses fixed weights and temporary context; the chat usually does not rewrite the weights.",
        "correctChoiceId": "v0279-training-q2-correct",
        "explain": "Insight strengthened. Normal chat inference can use context, but it usually does not rewrite weights.",
        "feedback": {
          "v0279-training-q2-correct": "Insight strengthened. Normal chat inference can use context, but it usually does not rewrite weights.",
          "v0279-training-q2-permanent-update": "Not quite. That would require a training process, not ordinary inference.",
          "v0279-training-q2-durable-memory": "This choice reveals a common mix-up. Context can shape the current chat without becoming a weight update.",
          "v0279-training-q2-optimizer-after-response": "Close, but optimizers update weights during training, not after every normal response."
        }
      },
      {
        "id": "v0279-training-q3",
        "question": "Why can training change how the model behaves tomorrow, while inference usually cannot?",
        "choices": [
          {
            "choiceId": "v0279-training-q3-correct",
            "text": "Training changes parameters that future runs reuse; inference uses temporary computations for the current run."
          },
          {
            "choiceId": "v0279-training-q3-optimizer-inference",
            "text": "Inference is where the optimizer changes weights for future runs."
          },
          {
            "choiceId": "v0279-training-q3-prompt-only",
            "text": "Training only changes the visible prompt text for one response."
          },
          {
            "choiceId": "v0279-training-q3-truth-guarantee",
            "text": "Training guarantees that every future answer will be true."
          }
        ],
        "answer": "Training changes parameters that future runs reuse; inference uses temporary computations for the current run.",
        "correctChoiceId": "v0279-training-q3-correct",
        "explain": "Good distinction. Durable parameters carry forward; inference-time states usually do not.",
        "feedback": {
          "v0279-training-q3-correct": "Good distinction. Durable parameters carry forward; inference-time states usually do not.",
          "v0279-training-q3-optimizer-inference": "Not quite. Optimizer-driven weight updates belong to training, not ordinary inference.",
          "v0279-training-q3-prompt-only": "Close, but prompt changes are temporary input changes; training changes learned numbers.",
          "v0279-training-q3-truth-guarantee": "This choice overclaims. Training can improve behavior, but it does not guarantee truth."
        }
      },
      {
        "id": "v0279-training-q4",
        "question": "In a training loop, which sequence is the durable learning path?",
        "choices": [
          {
            "choiceId": "v0279-training-q4-correct",
            "text": "Example -> prediction -> loss -> weight update."
          },
          {
            "choiceId": "v0279-training-q4-generation-loop",
            "text": "Prompt -> response token -> append -> next response token."
          },
          {
            "choiceId": "v0279-training-q4-search-context",
            "text": "Search -> outside passage -> current context -> answer."
          },
          {
            "choiceId": "v0279-training-q4-user-correction",
            "text": "User correction -> better answer -> permanent learning inside the same chat."
          }
        ],
        "answer": "Example -> prediction -> loss -> weight update.",
        "correctChoiceId": "v0279-training-q4-correct",
        "explain": "Insight strengthened. That is the weight-changing path.",
        "feedback": {
          "v0279-training-q4-correct": "Insight strengthened. That is the weight-changing path.",
          "v0279-training-q4-generation-loop": "Close, but that sequence describes inference/generation, not training.",
          "v0279-training-q4-search-context": "That describes a search or retrieval step. It can add temporary context; it does not by itself update weights.",
          "v0279-training-q4-user-correction": "Not quite. A correction can steer the current conversation, but durable learning requires a training process."
        }
      }
    ]
  },
  "pretraining": {
    "questions": [
      {
        "id": "v0279-pretraining-q1",
        "question": "During pretraining, what signal teaches the model broad language patterns across many examples?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q1-correct",
            "text": "Repeated prediction error/loss from next-token targets changes weights over many training steps."
          },
          {
            "choiceId": "v0279-pretraining-q1-live-chat",
            "text": "A user conversation at deployment permanently rewrites the model."
          },
          {
            "choiceId": "v0279-pretraining-q1-written-rules",
            "text": "A human writes every rule the model will follow."
          },
          {
            "choiceId": "v0279-pretraining-q1-perfect-copy",
            "text": "The model stores a perfect copy of every source document."
          }
        ],
        "answer": "Repeated prediction error/loss from next-token targets changes weights over many training steps.",
        "correctChoiceId": "v0279-pretraining-q1-correct",
        "explain": "Good distinction. Pretraining scales the training loop across many examples.",
        "feedback": {
          "v0279-pretraining-q1-correct": "Good distinction. Pretraining scales the training loop across many examples.",
          "v0279-pretraining-q1-live-chat": "Not quite. Pretraining happens before normal use; an ordinary chat usually does not rewrite weights.",
          "v0279-pretraining-q1-written-rules": "Close, but pretraining is learned from examples, not a complete rulebook written by hand.",
          "v0279-pretraining-q1-perfect-copy": "This choice reveals a common mix-up. Pretraining shapes weights; it is not perfect document storage."
        }
      },
      {
        "id": "v0279-pretraining-q2",
        "question": "Why can pretraining create broad capability without making the model a perfect library of its sources?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q2-correct",
            "text": "It shapes statistical patterns in weights; it does not create a searchable copy of every source."
          },
          {
            "choiceId": "v0279-pretraining-q2-private-files",
            "text": "It gives the model direct access to every private file on demand."
          },
          {
            "choiceId": "v0279-pretraining-q2-search-context",
            "text": "It inserts the original source into every future prompt context."
          },
          {
            "choiceId": "v0279-pretraining-q2-after-user-prompt",
            "text": "It happens only after a user asks a specific question."
          }
        ],
        "answer": "It shapes statistical patterns in weights; it does not create a searchable copy of every source.",
        "correctChoiceId": "v0279-pretraining-q2-correct",
        "explain": "Good distinction. Pretraining can shape broad ability without turning the model into a perfect source library.",
        "feedback": {
          "v0279-pretraining-q2-correct": "Good distinction. Pretraining can shape broad ability without turning the model into a perfect source library.",
          "v0279-pretraining-q2-private-files": "Not quite. Training data exposure is not the same as access to every private file.",
          "v0279-pretraining-q2-search-context": "Close, but adding source text to context is different from pretraining. Pretraining changes weights before use.",
          "v0279-pretraining-q2-after-user-prompt": "Pretraining happens before deployment. The user prompt later uses the pretrained weights."
        }
      },
      {
        "id": "v0279-pretraining-q3",
        "question": "If pretraining examples include many styles and task shapes, what can change inside the model?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q3-correct",
            "text": "Weights can shift so future prompts activate more useful language/code patterns."
          },
          {
            "choiceId": "v0279-pretraining-q3-current-context",
            "text": "The model’s current chat context becomes permanently larger."
          },
          {
            "choiceId": "v0279-pretraining-q3-interface",
            "text": "Only the app’s buttons, labels, or interface change."
          },
          {
            "choiceId": "v0279-pretraining-q3-safety-policy",
            "text": "Only a safety policy is added around the model."
          }
        ],
        "answer": "Weights can shift so future prompts activate more useful language/code patterns.",
        "correctChoiceId": "v0279-pretraining-q3-correct",
        "explain": "Good distinction. Pretraining changes reusable model structure before later prompts arrive.",
        "feedback": {
          "v0279-pretraining-q3-correct": "Good distinction. Pretraining changes reusable model structure before later prompts arrive.",
          "v0279-pretraining-q3-current-context": "Not quite. Context is temporary input; pretraining changes reusable weights before later prompts arrive.",
          "v0279-pretraining-q3-interface": "This describes product UI changes, not the model’s learned parameters.",
          "v0279-pretraining-q3-safety-policy": "Close, but a policy can shape a product around the model; pretraining changes the model’s reusable weights."
        }
      },
      {
        "id": "v0279-pretraining-q4",
        "question": "A base model produces fact-like text about public topics. What is the model-literate explanation?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q4-correct",
            "text": "Pretraining shaped weights with patterns from data, so the model may generate fact-like text without retrieving the original page."
          },
          {
            "choiceId": "v0279-pretraining-q4-web-every-time",
            "text": "It must be browsing the web by itself for every answer."
          },
          {
            "choiceId": "v0279-pretraining-q4-conscious-memory",
            "text": "It must consciously remember reading those pages."
          },
          {
            "choiceId": "v0279-pretraining-q4-finetuning-alone",
            "text": "Fine-tuning alone explains all broad model knowledge."
          }
        ],
        "answer": "Pretraining shaped weights with patterns from data, so the model may generate fact-like text without retrieving the original page.",
        "correctChoiceId": "v0279-pretraining-q4-correct",
        "explain": "Insight strengthened. Source-like output can come from pretrained patterns, but it is not the same as cited evidence.",
        "feedback": {
          "v0279-pretraining-q4-correct": "Insight strengthened. Source-like output can come from pretrained patterns, but it is not the same as cited evidence.",
          "v0279-pretraining-q4-web-every-time": "Not quite. Some systems browse or retrieve, but a base model can also generate fact-like text from pretrained weights.",
          "v0279-pretraining-q4-conscious-memory": "That gives the model too much mind. It has learned weights, not conscious recollection.",
          "v0279-pretraining-q4-finetuning-alone": "Close, but fine-tuning is targeted shaping after broad pretraining; it does not usually explain the whole foundation."
        }
      }
    ]
  },
  "overfitting-generalization": {
    "questions": [
      {
        "id": "v0279-overfitting-generalization-q1",
        "question": "A model gets every training example right but fails on new validation examples. What problem is showing up?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q1-correct",
            "text": "Overfitting: the model fit training examples too narrowly instead of learning patterns that generalize."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-generalization",
            "text": "Generalization: the model is working well on unseen cases."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-better-training",
            "text": "Better training: the model has clearly learned the general rule."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-inference",
            "text": "Inference: the model is simply generating one token at a time."
          }
        ],
        "answer": "Overfitting: the model fit training examples too narrowly instead of learning patterns that generalize.",
        "correctChoiceId": "v0279-overfitting-generalization-q1-correct",
        "explain": "Good diagnosis. The set-aside validation examples reveal whether the pattern transfers.",
        "feedback": {
          "v0279-overfitting-generalization-q1-correct": "Good diagnosis. The set-aside validation examples reveal whether the pattern transfers.",
          "v0279-overfitting-generalization-q1-generalization": "Not quite. Generalization means good performance on new examples; this scenario shows the opposite.",
          "v0279-overfitting-generalization-q1-better-training": "Not quite. If it fails on new validation examples, high training performance is not enough evidence of generalization.",
          "v0279-overfitting-generalization-q1-inference": "Close, but inference is normal model use; overfitting is a training/evaluation failure mode."
        }
      },
      {
        "id": "v0279-overfitting-generalization-q2",
        "question": "Why do model builders test on set-aside validation examples instead of only training examples?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q2-correct",
            "text": "Set-aside validation examples checks whether learned patterns work on examples the model did not train on."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-extra-training",
            "text": "Validation data is just extra training data used to lower loss."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-training-proves-all",
            "text": "Training examples alone prove the model will work everywhere."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-loss-truth",
            "text": "A lower loss always proves every future answer is true."
          }
        ],
        "answer": "Set-aside validation examples checks whether learned patterns work on examples the model did not train on.",
        "correctChoiceId": "v0279-overfitting-generalization-q2-correct",
        "explain": "Insight strengthened. Validation is about transfer, not memorized training performance.",
        "feedback": {
          "v0279-overfitting-generalization-q2-correct": "Insight strengthened. Validation is about transfer, not memorized training performance.",
          "v0279-overfitting-generalization-q2-extra-training": "Not quite. Validation data is saved for testing to check transfer; it should not simply be another set of examples used to fit weights.",
          "v0279-overfitting-generalization-q2-training-proves-all": "This choice reveals the exact overfitting risk. Seen examples are not enough evidence.",
          "v0279-overfitting-generalization-q2-loss-truth": "Close, but lower loss is not a truth guarantee, especially outside the tested examples."
        }
      },
      {
        "id": "v0279-overfitting-generalization-q3",
        "question": "A model trained heavily on one narrow answer template works on that template but struggles with varied new prompts. What should a model-literate learner suspect?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q3-correct",
            "text": "It may have fit the narrow examples too closely instead of learning a pattern that generalizes."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-prompt-rewrite",
            "text": "The prompts permanently rewrote the model during inference."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-conscious-choice",
            "text": "The model is definitely conscious but choosing not to answer."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-rules-always-better",
            "text": "Rule-based AI is always better than learned models."
          }
        ],
        "answer": "It may have fit the narrow examples too closely instead of learning a pattern that generalizes.",
        "correctChoiceId": "v0279-overfitting-generalization-q3-correct",
        "explain": "Good distinction. Targeted training can help, but narrow training can also make behavior brittle.",
        "feedback": {
          "v0279-overfitting-generalization-q3-correct": "Good distinction. Targeted training can help, but narrow training can also make behavior brittle.",
          "v0279-overfitting-generalization-q3-prompt-rewrite": "Not quite. The issue is training behavior, not prompts rewriting weights during inference.",
          "v0279-overfitting-generalization-q3-conscious-choice": "That gives the model too much mind. The issue is brittle transfer, not intention.",
          "v0279-overfitting-generalization-q3-rules-always-better": "This overgeneralizes. The issue is narrow training behavior, not proof that rules always beat learned models."
        }
      }
    ]
  },
  "fine-tuning": {
    "questions": [
      {
        "id": "v02710-fine-tuning-q1",
        "question": "A team wants a support assistant to answer in a durable house style across future conversations. Which move is closest to fine-tuning?",
        "choices": [
          {
            "choiceId": "v02710-fine-tuning-q1-correct",
            "text": "Run additional training that changes weights or adapter behavior for future responses."
          },
          {
            "choiceId": "v02710-fine-tuning-q1-better-prompt",
            "text": "Write one clearer prompt for the current chat."
          },
          {
            "choiceId": "v02710-fine-tuning-q1-rag",
            "text": "Retrieve one policy PDF into the current context."
          },
          {
            "choiceId": "v02710-fine-tuning-q1-sampling",
            "text": "Sample the next token from the current probability cloud."
          }
        ],
        "answer": "Run additional training that changes weights or adapter behavior for future responses.",
        "correctChoiceId": "v02710-fine-tuning-q1-correct",
        "explain": "Good distinction. Fine-tuning is durable shaping after pretraining.",
        "feedback": {
          "v02710-fine-tuning-q1-correct": "Good distinction. Fine-tuning is durable shaping after pretraining.",
          "v02710-fine-tuning-q1-better-prompt": "Not quite. A prompt can steer the current run, but fine-tuning changes future behavior through training.",
          "v02710-fine-tuning-q1-rag": "Close, but RAG adds temporary context. Fine-tuning is a training process that durably shapes behavior.",
          "v02710-fine-tuning-q1-sampling": "That describes decoding during inference. It chooses a token; it does not adapt the model for future runs."
        }
      },
      {
        "id": "v02710-fine-tuning-q2",
        "question": "A base model is adapted on thousands of institution-specific examples, then later answers new users in that style. What changed most directly?",
        "choices": [
          {
            "choiceId": "v02710-fine-tuning-q2-correct",
            "text": "The adapted model’s weights or adapter behavior can carry that pattern into later inference runs."
          },
          {
            "choiceId": "v02710-fine-tuning-q2-context-only",
            "text": "Only the current context window got larger."
          },
          {
            "choiceId": "v02710-fine-tuning-q2-memory",
            "text": "The model became conscious of the institution’s norms."
          },
          {
            "choiceId": "v02710-fine-tuning-q2-rag-search",
            "text": "The model must search the institution’s files every time."
          }
        ],
        "answer": "The adapted model’s weights or adapter behavior can carry that pattern into later inference runs.",
        "correctChoiceId": "v02710-fine-tuning-q2-correct",
        "explain": "Insight strengthened. Fine-tuning makes a reusable model change, not just a one-chat hint.",
        "feedback": {
          "v02710-fine-tuning-q2-correct": "Insight strengthened. Fine-tuning makes a reusable model change, not just a one-chat hint.",
          "v02710-fine-tuning-q2-context-only": "Not quite. A larger context window is temporary input space; fine-tuning changes reusable behavior.",
          "v02710-fine-tuning-q2-memory": "That gives the model too much mind. The behavior can be shaped without conscious commitment to norms.",
          "v02710-fine-tuning-q2-rag-search": "Close, but fine-tuning and retrieval are different. Retrieval may be added, but fine-tuned behavior can persist in weights or adapters."
        }
      },
      {
        "id": "v02710-fine-tuning-q3",
        "question": "If fine-tuning is used for alignment, what does that mean about future model behavior?",
        "choices": [
          {
            "choiceId": "v02710-fine-tuning-q3-correct",
            "text": "Training can make some instruction-following or preference patterns more likely in later responses."
          },
          {
            "choiceId": "v02710-fine-tuning-q3-perfect-safety",
            "text": "Every future answer is guaranteed safe and true."
          },
          {
            "choiceId": "v02710-fine-tuning-q3-system-prompt-only",
            "text": "Only the visible system prompt changed for one session."
          },
          {
            "choiceId": "v02710-fine-tuning-q3-inner-values",
            "text": "The model acquired human values and moral agency."
          }
        ],
        "answer": "Training can make some instruction-following or preference patterns more likely in later responses.",
        "correctChoiceId": "v02710-fine-tuning-q3-correct",
        "explain": "Good distinction. Fine-tuning can support alignment by durably shaping output patterns.",
        "feedback": {
          "v02710-fine-tuning-q3-correct": "Good distinction. Fine-tuning can support alignment by durably shaping output patterns.",
          "v02710-fine-tuning-q3-perfect-safety": "Not quite. Fine-tuning can improve behavior, but it does not guarantee truth or safety.",
          "v02710-fine-tuning-q3-system-prompt-only": "Close, but a system prompt steers the current run. Fine-tuning is durable training.",
          "v02710-fine-tuning-q3-inner-values": "That gives the model too much mind. Fine-tuning changes output patterns; it does not create moral agency."
        }
      }
    ]
  },
  "alignment": {
    "questions": [
      {
        "id": "v02710-alignment-q1",
        "question": "An alignment-shaped assistant refuses a harmful request and follows a safer instruction instead. What should a model-literate learner conclude?",
        "choices": [
          {
            "choiceId": "v02710-alignment-q1-correct",
            "text": "Its behavior was shaped toward instructions and safety boundaries, but that does not prove moral understanding."
          },
          {
            "choiceId": "v02710-alignment-q1-conscious",
            "text": "The model must understand morality the way a person does."
          },
          {
            "choiceId": "v02710-alignment-q1-truth",
            "text": "Every answer from the assistant is now guaranteed true."
          },
          {
            "choiceId": "v02710-alignment-q1-no-model",
            "text": "The LLM stopped using learned weights and became a rulebook."
          }
        ],
        "answer": "Its behavior was shaped toward instructions and safety boundaries, but that does not prove moral understanding.",
        "correctChoiceId": "v02710-alignment-q1-correct",
        "explain": "Good distinction. Alignment shapes behavior; it is not magic morality.",
        "feedback": {
          "v02710-alignment-q1-correct": "Good distinction. Alignment shapes behavior; it is not magic morality.",
          "v02710-alignment-q1-conscious": "That gives the model too much mind. Refusal behavior can be shaped without human moral understanding.",
          "v02710-alignment-q1-truth": "Not quite. Alignment can shape behavior, but it does not guarantee factual truth.",
          "v02710-alignment-q1-no-model": "Close, but an aligned product can still use a learned model plus rules, filters, or policies."
        }
      },
      {
        "id": "v02710-alignment-q2",
        "question": "A product uses instruction fine-tuning, a system prompt, and a policy filter around one LLM. Which alignment map is most useful?",
        "choices": [
          {
            "choiceId": "v02710-alignment-q2-correct",
            "text": "Some alignment changes can be durable training changes, while other controls steer or filter the current run."
          },
          {
            "choiceId": "v02710-alignment-q2-all-weights",
            "text": "Every alignment layer permanently rewrites the model weights."
          },
          {
            "choiceId": "v02710-alignment-q2-only-prompt",
            "text": "Alignment is only a better prompt typed by the user."
          },
          {
            "choiceId": "v02710-alignment-q2-sampling-only",
            "text": "Alignment is the same thing as sampling the most probable token."
          }
        ],
        "answer": "Some alignment changes can be durable training changes, while other controls steer or filter the current run.",
        "correctChoiceId": "v02710-alignment-q2-correct",
        "explain": "Insight strengthened. Alignment can happen through several layers, not one magic switch.",
        "feedback": {
          "v02710-alignment-q2-correct": "Insight strengthened. Alignment can happen through several layers, not one magic switch.",
          "v02710-alignment-q2-all-weights": "Not quite. Fine-tuning may change weights, but system prompts and filters can steer behavior at runtime.",
          "v02710-alignment-q2-only-prompt": "Close, but alignment can include training, policies, evaluation, and runtime controls beyond the user prompt.",
          "v02710-alignment-q2-sampling-only": "Sampling chooses a next token from probabilities. Alignment shapes or constrains behavior around that process."
        }
      },
      {
        "id": "v02710-alignment-q3",
        "question": "Why do teams evaluate aligned models with tests and human feedback after training or deployment?",
        "choices": [
          {
            "choiceId": "v02710-alignment-q3-correct",
            "text": "Because shaped behavior can still fail, drift, or create unexpected tradeoffs in new situations."
          },
          {
            "choiceId": "v02710-alignment-q3-conscious-test",
            "text": "To check whether the model has developed a conscience."
          },
          {
            "choiceId": "v02710-alignment-q3-no-need",
            "text": "Because aligned models no longer need human review."
          },
          {
            "choiceId": "v02710-alignment-q3-loss-only",
            "text": "Because lower training loss alone proves the model is safe."
          }
        ],
        "answer": "Because shaped behavior can still fail, drift, or create unexpected tradeoffs in new situations.",
        "correctChoiceId": "v02710-alignment-q3-correct",
        "explain": "Good distinction. Alignment needs evaluation; it is not a one-time guarantee.",
        "feedback": {
          "v02710-alignment-q3-correct": "Good distinction. Alignment needs evaluation; it is not a one-time guarantee.",
          "v02710-alignment-q3-conscious-test": "Not quite. Evaluation checks behavior and outcomes, not inner conscience.",
          "v02710-alignment-q3-no-need": "This choice overclaims. Aligned systems can still need review, monitoring, and accountability.",
          "v02710-alignment-q3-loss-only": "Close, but loss alone is not a full safety or usefulness evaluation."
        }
      },
      {
        "id": "v02710-alignment-q4",
        "question": "A guardrail blocks one unsafe response from reaching the user. What changed most directly?",
        "choices": [
          {
            "choiceId": "v02710-alignment-q4-correct",
            "text": "A policy or filter layer affected the visible response; that does not necessarily mean the model weights changed."
          },
          {
            "choiceId": "v02710-alignment-q4-finetune",
            "text": "The base model was definitely fine-tuned at that moment."
          },
          {
            "choiceId": "v02710-alignment-q4-truth",
            "text": "The response became guaranteed factual because it passed a guardrail."
          },
          {
            "choiceId": "v02710-alignment-q4-awareness",
            "text": "The model realized the request was wrong."
          }
        ],
        "answer": "A policy or filter layer affected the visible response; that does not necessarily mean the model weights changed.",
        "correctChoiceId": "v02710-alignment-q4-correct",
        "explain": "Good distinction. Guardrails can be runtime controls around a model.",
        "feedback": {
          "v02710-alignment-q4-correct": "Good distinction. Guardrails can be runtime controls around a model.",
          "v02710-alignment-q4-finetune": "Not quite. A filter can block output during runtime without retraining the model.",
          "v02710-alignment-q4-truth": "Passing a guardrail is not the same as being true. Evidence and review can still matter.",
          "v02710-alignment-q4-awareness": "That gives the model too much mind. The visible behavior can come from shaped model behavior or surrounding controls."
        }
      }
    ]
  },
  "inference": {
    "questions": [
      {
        "id": "v02710-inference-q1",
        "question": "During ordinary inference, the current context enters the model. What changes temporarily, and what usually stays fixed?",
        "choices": [
          {
            "choiceId": "v02710-inference-q1-correct",
            "text": "Temporary activations and hidden states change; learned weights usually stay fixed."
          },
          {
            "choiceId": "v02710-inference-q1-weights-change",
            "text": "The learned weights change after every user prompt."
          },
          {
            "choiceId": "v02710-inference-q1-dataset",
            "text": "The training dataset changes to include the new prompt."
          },
          {
            "choiceId": "v02710-inference-q1-conscious",
            "text": "The model’s conscious attention shifts to the user’s intent."
          }
        ],
        "answer": "Temporary activations and hidden states change; learned weights usually stay fixed.",
        "correctChoiceId": "v02710-inference-q1-correct",
        "explain": "Good distinction. Inference uses the map without redrawing it.",
        "feedback": {
          "v02710-inference-q1-correct": "Good distinction. Inference uses the map without redrawing it.",
          "v02710-inference-q1-weights-change": "Not quite. Ordinary inference can use context, but it usually does not rewrite weights.",
          "v02710-inference-q1-dataset": "This choice reveals a common mix-up. A prompt can be current context without joining the training dataset.",
          "v02710-inference-q1-conscious": "That gives the model too much mind. Inference computes temporary vectors; it is not conscious attention."
        }
      },
      {
        "id": "v02710-inference-q2",
        "question": "In one inference step, which trace best matches the model’s next-token path?",
        "choices": [
          {
            "choiceId": "v02710-inference-q2-correct",
            "text": "Context enters a forward pass, temporary states form, logits are produced, and sampling can choose a token."
          },
          {
            "choiceId": "v02710-inference-q2-training-loop",
            "text": "Example enters training, loss updates weights, and a future model checkpoint is saved."
          },
          {
            "choiceId": "v02710-inference-q2-rag-loop",
            "text": "Retriever searches outside documents, then the model permanently learns the snippets."
          },
          {
            "choiceId": "v02710-inference-q2-tokenizer-only",
            "text": "Tokenizer splits text and the answer appears without model layers."
          }
        ],
        "answer": "Context enters a forward pass, temporary states form, logits are produced, and sampling can choose a token.",
        "correctChoiceId": "v02710-inference-q2-correct",
        "explain": "Insight strengthened. That is the live next-token path through inference.",
        "feedback": {
          "v02710-inference-q2-correct": "Insight strengthened. That is the live next-token path through inference.",
          "v02710-inference-q2-training-loop": "Close, but that is a training path. Inference uses existing weights to produce the next-token scores.",
          "v02710-inference-q2-rag-loop": "Retrieval can add context before inference, but it does not by itself make the model permanently learn snippets.",
          "v02710-inference-q2-tokenizer-only": "Tokenization prepares input, but inference still runs model layers to produce scores."
        }
      },
      {
        "id": "v02710-inference-q3",
        "question": "A chatbot remembers an earlier line in the same conversation and uses it in the next answer. What is the best model-level explanation?",
        "choices": [
          {
            "choiceId": "v02710-inference-q3-correct",
            "text": "The earlier line is still in the current context, so fixed weights can use it during inference."
          },
          {
            "choiceId": "v02710-inference-q3-weight-memory",
            "text": "The earlier line was written into the model’s weights."
          },
          {
            "choiceId": "v02710-inference-q3-training-now",
            "text": "The chatbot fine-tuned itself on the earlier line."
          },
          {
            "choiceId": "v02710-inference-q3-search-all",
            "text": "The model searched every document it was pretrained on."
          }
        ],
        "answer": "The earlier line is still in the current context, so fixed weights can use it during inference.",
        "correctChoiceId": "v02710-inference-q3-correct",
        "explain": "Good distinction. Context can feel like memory while still being temporary input.",
        "feedback": {
          "v02710-inference-q3-correct": "Good distinction. Context can feel like memory while still being temporary input.",
          "v02710-inference-q3-weight-memory": "Not quite. Same-conversation context is temporary input, not necessarily a weight update.",
          "v02710-inference-q3-training-now": "Close, but adaptation within a context window is not the same as fine-tuning.",
          "v02710-inference-q3-search-all": "This describes search better than ordinary inference. The model can use visible context without searching training sources."
        }
      },
      {
        "id": "v02710-inference-q4",
        "question": "If ordinary inference normally does not update weights, what follows for future conversations?",
        "choices": [
          {
            "choiceId": "v02710-inference-q4-correct",
            "text": "A useful answer now does not automatically teach the base model to behave differently tomorrow."
          },
          {
            "choiceId": "v02710-inference-q4-auto-learn",
            "text": "Every good answer automatically becomes permanent skill."
          },
          {
            "choiceId": "v02710-inference-q4-no-context",
            "text": "The current prompt cannot affect the answer at all."
          },
          {
            "choiceId": "v02710-inference-q4-no-risk",
            "text": "There is no need to review outputs because inference is temporary."
          }
        ],
        "answer": "A useful answer now does not automatically teach the base model to behave differently tomorrow.",
        "correctChoiceId": "v02710-inference-q4-correct",
        "explain": "Insight strengthened. Inference can be useful without being durable training.",
        "feedback": {
          "v02710-inference-q4-correct": "Insight strengthened. Inference can be useful without being durable training.",
          "v02710-inference-q4-auto-learn": "Not quite. Durable skill changes require training or another model-update process.",
          "v02710-inference-q4-no-context": "Close, but fixed weights can still respond differently to different current contexts.",
          "v02710-inference-q4-no-risk": "This choice overclaims. Temporary outputs can still affect people and decisions, so review can matter."
        }
      }
    ]
  },
  "prompt-response": {
    "questions": [
      {
        "id": "v02710-prompt-response-q1",
        "question": "A user gives a complete prompt, then the model begins writing response tokens. Which boundary matters most?",
        "choices": [
          {
            "choiceId": "v02710-prompt-response-q1-correct",
            "text": "Prompt tokens are given to the model; response tokens are generated and then appended to context."
          },
          {
            "choiceId": "v02710-prompt-response-q1-all-user",
            "text": "Both prompt and response tokens were typed by the user."
          },
          {
            "choiceId": "v02710-prompt-response-q1-all-at-once",
            "text": "The model writes the whole response at once after reading the prompt."
          },
          {
            "choiceId": "v02710-prompt-response-q1-weight-update",
            "text": "Each response token permanently updates the model’s weights."
          }
        ],
        "answer": "Prompt tokens are given to the model; response tokens are generated and then appended to context.",
        "correctChoiceId": "v02710-prompt-response-q1-correct",
        "explain": "Good distinction. Prompt is given; response is generated and appended.",
        "feedback": {
          "v02710-prompt-response-q1-correct": "Good distinction. Prompt is given; response is generated and appended.",
          "v02710-prompt-response-q1-all-user": "Not quite. The user provides the prompt; the model generates response tokens.",
          "v02710-prompt-response-q1-all-at-once": "Close, but the model generates response tokens step by step.",
          "v02710-prompt-response-q1-weight-update": "This choice reveals a common mix-up. Response tokens can shape the current run without updating weights."
        }
      },
      {
        "id": "v02710-prompt-response-q2",
        "question": "After the model chooses one next response token, what does the next inference step see?",
        "choices": [
          {
            "choiceId": "v02710-prompt-response-q2-correct",
            "text": "The original prompt plus the response so far, including the newly appended token."
          },
          {
            "choiceId": "v02710-prompt-response-q2-only-new-token",
            "text": "Only the newly chosen token, with the prompt removed."
          },
          {
            "choiceId": "v02710-prompt-response-q2-weight-memory",
            "text": "A permanent memory of the token stored in model weights."
          },
          {
            "choiceId": "v02710-prompt-response-q2-softmax-removed",
            "text": "No context, because softmax disappears after one token."
          }
        ],
        "answer": "The original prompt plus the response so far, including the newly appended token.",
        "correctChoiceId": "v02710-prompt-response-q2-correct",
        "explain": "Insight strengthened. The context grows as generated response tokens are appended.",
        "feedback": {
          "v02710-prompt-response-q2-correct": "Insight strengthened. The context grows as generated response tokens are appended.",
          "v02710-prompt-response-q2-only-new-token": "Not quite. The next step can use the prompt and response-so-far that remain in context.",
          "v02710-prompt-response-q2-weight-memory": "Close, but using a token later in the run is context, not a weight update.",
          "v02710-prompt-response-q2-softmax-removed": "Softmax can help choose a token, but the chosen token can still be appended to the next context."
        }
      },
      {
        "id": "v02710-prompt-response-q3",
        "question": "A generated response improves after the user adds a clarifying sentence. What changed most directly?",
        "choices": [
          {
            "choiceId": "v02710-prompt-response-q3-correct",
            "text": "The current prompt/context changed, so the next response tokens were generated from better input."
          },
          {
            "choiceId": "v02710-prompt-response-q3-finetuned",
            "text": "The model was fine-tuned by the clarifying sentence."
          },
          {
            "choiceId": "v02710-prompt-response-q3-conscious",
            "text": "The model understood its mistake like a person and decided to improve."
          },
          {
            "choiceId": "v02710-prompt-response-q3-no-effect",
            "text": "Prompts cannot affect generated response tokens."
          }
        ],
        "answer": "The current prompt/context changed, so the next response tokens were generated from better input.",
        "correctChoiceId": "v02710-prompt-response-q3-correct",
        "explain": "Good distinction. Better context can improve the current response without training the model.",
        "feedback": {
          "v02710-prompt-response-q3-correct": "Good distinction. Better context can improve the current response without training the model.",
          "v02710-prompt-response-q3-finetuned": "Not quite. A clarifying sentence can steer the current run; fine-tuning is additional training.",
          "v02710-prompt-response-q3-conscious": "That gives the model too much mind. Better output can come from better context.",
          "v02710-prompt-response-q3-no-effect": "Close, but fixed weights still process different prompts into different response probabilities."
        }
      }
    ]
  },
  "tokens": {
    "questions": [
      {
        "id": "v02710-tokens-q1",
        "question": "A tokenizer splits “startled.” into pieces like “start”, “led”, and “.” What should that tell a learner?",
        "choices": [
          {
            "choiceId": "v02710-tokens-q1-correct",
            "text": "Tokens can be uneven text chunks, including word pieces and punctuation."
          },
          {
            "choiceId": "v02710-tokens-q1-whole-word",
            "text": "Every token must be a complete dictionary word."
          },
          {
            "choiceId": "v02710-tokens-q1-memory",
            "text": "Each token is a permanent memory stored in the model."
          },
          {
            "choiceId": "v02710-tokens-q1-concept",
            "text": "Each token is exactly one human concept."
          }
        ],
        "answer": "Tokens can be uneven text chunks, including word pieces and punctuation.",
        "correctChoiceId": "v02710-tokens-q1-correct",
        "explain": "Good distinction. Tokens are model-readable chunks, not always whole words.",
        "feedback": {
          "v02710-tokens-q1-correct": "Good distinction. Tokens are model-readable chunks, not always whole words.",
          "v02710-tokens-q1-whole-word": "Not quite. Tokenizers can split words, punctuation, spaces, or other chunks.",
          "v02710-tokens-q1-memory": "This choice reveals a common mix-up. A token is a representation chunk, not memory by itself.",
          "v02710-tokens-q1-concept": "Close, but token boundaries do not perfectly match human concepts or meanings."
        }
      },
      {
        "id": "v02710-tokens-q2",
        "question": "Before transformer layers process text, which tokens-to-IDs-to-embeddings path comes first?",
        "choices": [
          {
            "choiceId": "v02710-tokens-q2-correct",
            "text": "Text is split into tokens, tokens map to token IDs, and IDs look up embeddings."
          },
          {
            "choiceId": "v02710-tokens-q2-raw-english",
            "text": "Raw English sentences move through every layer without numerical representation."
          },
          {
            "choiceId": "v02710-tokens-q2-weights-first",
            "text": "Weights are rewritten before text becomes tokens."
          },
          {
            "choiceId": "v02710-tokens-q2-response-first",
            "text": "The model generates the finished response before tokenization happens."
          }
        ],
        "answer": "Text is split into tokens, tokens map to token IDs, and IDs look up embeddings.",
        "correctChoiceId": "v02710-tokens-q2-correct",
        "explain": "Insight strengthened. Tokenization starts the bridge from text to numerical computation.",
        "feedback": {
          "v02710-tokens-q2-correct": "Insight strengthened. Tokenization starts the bridge from text to numerical computation.",
          "v02710-tokens-q2-raw-english": "Not quite. The model needs numerical representations, starting with tokens and IDs.",
          "v02710-tokens-q2-weights-first": "Close, but tokenization prepares the input; it does not rewrite weights.",
          "v02710-tokens-q2-response-first": "Generation also uses tokens. Text needs token representation before model layers can process it."
        }
      },
      {
        "id": "v02710-tokens-q3",
        "question": "Both the user prompt and the generated response eventually appear as text. How does tokenization treat them?",
        "choices": [
          {
            "choiceId": "v02710-tokens-q3-correct",
            "text": "Prompt text and generated response text can both be represented as tokens."
          },
          {
            "choiceId": "v02710-tokens-q3-prompt-only",
            "text": "Only prompt text becomes tokens; response text skips token IDs."
          },
          {
            "choiceId": "v02710-tokens-q3-response-only",
            "text": "Only response text becomes tokens; prompts stay as raw English."
          },
          {
            "choiceId": "v02710-tokens-q3-training",
            "text": "Tokenizing either one permanently trains the model."
          }
        ],
        "answer": "Prompt text and generated response text can both be represented as tokens.",
        "correctChoiceId": "v02710-tokens-q3-correct",
        "explain": "Good distinction. Tokenization applies to text entering and leaving the generation loop.",
        "feedback": {
          "v02710-tokens-q3-correct": "Good distinction. Tokenization applies to text entering and leaving the generation loop.",
          "v02710-tokens-q3-prompt-only": "Not quite. Generated response tokens are token IDs before being displayed as text.",
          "v02710-tokens-q3-response-only": "Close, but prompts also need token representation before model processing.",
          "v02710-tokens-q3-training": "This choice reveals a common mix-up. Tokenization represents text; it does not update weights."
        }
      }
    ]
  },
  "token-ids": {
    "questions": [
      {
        "id": "v02710-token-ids-q1",
        "question": "After tokenization, the token “dog” maps to an integer ID. What does the model use that ID for next?",
        "choices": [
          {
            "choiceId": "v02710-token-ids-q1-correct",
            "text": "To look up a learned starting vector in the embedding table."
          },
          {
            "choiceId": "v02710-token-ids-q1-meaning",
            "text": "To store the complete meaning of dog inside the number itself."
          },
          {
            "choiceId": "v02710-token-ids-q1-memory",
            "text": "To permanently remember this user’s sentence."
          },
          {
            "choiceId": "v02710-token-ids-q1-skip",
            "text": "To skip embeddings and tensors entirely."
          }
        ],
        "answer": "To look up a learned starting vector in the embedding table.",
        "correctChoiceId": "v02710-token-ids-q1-correct",
        "explain": "Good distinction. The ID is a lookup key for an embedding vector.",
        "feedback": {
          "v02710-token-ids-q1-correct": "Good distinction. The ID is a lookup key for an embedding vector.",
          "v02710-token-ids-q1-meaning": "Not quite. The number itself is not the meaning; it points to learned numerical patterns.",
          "v02710-token-ids-q1-memory": "This choice reveals a common mix-up. Token IDs represent chunks; they do not store a user memory.",
          "v02710-token-ids-q1-skip": "Close, but the ID is a lookup key; embeddings and tensors still carry numerical representation forward."
        }
      },
      {
        "id": "v02710-token-ids-q2",
        "question": "A learner says “982 means cat because the ID is the meaning.” What correction is most model-literate?",
        "choices": [
          {
            "choiceId": "v02710-token-ids-q2-correct",
            "text": "982 is a lookup number for a token; meaning comes from learned patterns around embeddings and model layers."
          },
          {
            "choiceId": "v02710-token-ids-q2-conscious",
            "text": "982 means cat because the model consciously understands the number."
          },
          {
            "choiceId": "v02710-token-ids-q2-truth",
            "text": "982 guarantees every sentence about cats will be true."
          },
          {
            "choiceId": "v02710-token-ids-q2-random-every-run",
            "text": "982 is randomly redefined every time the user sends a prompt."
          }
        ],
        "answer": "982 is a lookup number for a token; meaning comes from learned patterns around embeddings and model layers.",
        "correctChoiceId": "v02710-token-ids-q2-correct",
        "explain": "Insight strengthened. The ID points into the system; it is not understanding by itself.",
        "feedback": {
          "v02710-token-ids-q2-correct": "Insight strengthened. The ID points into the system; it is not understanding by itself.",
          "v02710-token-ids-q2-conscious": "That gives the model too much mind. A lookup number does not imply conscious understanding.",
          "v02710-token-ids-q2-truth": "Not quite. Token IDs do not guarantee factual output.",
          "v02710-token-ids-q2-random-every-run": "Close, but token ID mappings are fixed for a tokenizer/model setup; sampling randomness is a different step."
        }
      },
      {
        "id": "v02710-token-ids-q3",
        "question": "During generation, the model chooses a next response token ID before the user sees text. What happens after that?",
        "choices": [
          {
            "choiceId": "v02710-token-ids-q3-correct",
            "text": "The chosen ID can be displayed as text and appended as a response token in the current context."
          },
          {
            "choiceId": "v02710-token-ids-q3-weight-update",
            "text": "The chosen ID permanently updates the model weights."
          },
          {
            "choiceId": "v02710-token-ids-q3-raw-word",
            "text": "The model skips IDs and chooses only raw human words."
          },
          {
            "choiceId": "v02710-token-ids-q3-retrieve-source",
            "text": "The ID retrieves the original training document for that word."
          }
        ],
        "answer": "The chosen ID can be displayed as text and appended as a response token in the current context.",
        "correctChoiceId": "v02710-token-ids-q3-correct",
        "explain": "Good distinction. Generated tokens are IDs before they become visible text.",
        "feedback": {
          "v02710-token-ids-q3-correct": "Good distinction. Generated tokens are IDs before they become visible text.",
          "v02710-token-ids-q3-weight-update": "Not quite. The chosen token can affect the next context without changing weights.",
          "v02710-token-ids-q3-raw-word": "Close, but the model works with token IDs before text is displayed.",
          "v02710-token-ids-q3-retrieve-source": "This describes retrieval better than token ID lookup. Token IDs point to token representations, not original documents."
        }
      }
    ]
  }
} as const

export type CheckpointBankLessonId = keyof typeof FIRST_TWELVE_CHECKPOINT_BANK_V02710

export function hasV02710CheckpointBank(lessonId: string): lessonId is CheckpointBankLessonId {
  return Object.prototype.hasOwnProperty.call(FIRST_TWELVE_CHECKPOINT_BANK_V02710, lessonId)
}
