// Generated by scripts/generate-checkpoint-live-pilot-v0279.mjs.
// This development pilot overrides only the first six Journey checkpoints.

export const ACTIVE_CHECKPOINT_BANK = 'v0.27.9-first-six'

export const FIRST_SIX_CHECKPOINT_BANK_V0279 = {
  "what-is-llm": {
    "questions": [
      {
        "id": "v0279-what-is-llm-q1",
        "question": "When an LLM answers a prompt by generating one token at a time, what is the model doing at each step?",
        "choices": [
          {
            "choiceId": "v0279-what-is-llm-q1-correct",
            "text": "It scores possible next tokens from the current context, selects one, appends it, and repeats."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-conscious-reader",
            "text": "It reads with conscious understanding, then writes the whole answer at once."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-hidden-search",
            "text": "It searches a hidden database and copies the best matching passage."
          },
          {
            "choiceId": "v0279-what-is-llm-q1-weight-change",
            "text": "It changes its weights each time the user sends a new prompt."
          }
        ],
        "answer": "It scores possible next tokens from the current context, selects one, appends it, and repeats.",
        "correctChoiceId": "v0279-what-is-llm-q1-correct",
        "explain": "Good distinction. The model is using fixed learned weights and temporary context to make the next-token step.",
        "feedback": {
          "v0279-what-is-llm-q1-correct": "Good distinction. The model is using fixed learned weights and temporary context to make the next-token step.",
          "v0279-what-is-llm-q1-conscious-reader": "Not quite. That gives the model too much mind. Fluent behavior can happen without awareness.",
          "v0279-what-is-llm-q1-hidden-search": "This choice reveals a common mix-up. Search can be added around a model, but a plain LLM generates from context and learned weights.",
          "v0279-what-is-llm-q1-weight-change": "That would be true only if a separate training process updated weights. Ordinary inference usually leaves weights fixed."
        }
      },
      {
        "id": "v0279-what-is-llm-q2",
        "question": "An LLM gives a fluent explanation of a poem. What should a model-literate learner conclude?",
        "choices": [
          {
            "choiceId": "v0279-what-is-llm-q2-correct",
            "text": "It generated response tokens from context and learned patterns; fluency does not prove awareness."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-inner-awareness",
            "text": "It must have inner awareness because the explanation sounds human."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-hidden-source",
            "text": "It must have found a hidden perfect source and copied the interpretation."
          },
          {
            "choiceId": "v0279-what-is-llm-q2-prompt-learning",
            "text": "The poem prompt permanently taught the base model a new skill."
          }
        ],
        "answer": "It generated response tokens from context and learned patterns; fluency does not prove awareness.",
        "correctChoiceId": "v0279-what-is-llm-q2-correct",
        "explain": "Insight strengthened. This is the fluent-behavior-without-awareness boundary Prompt Life wants learners to hold.",
        "feedback": {
          "v0279-what-is-llm-q2-correct": "Insight strengthened. This is the fluent-behavior-without-awareness boundary Prompt Life wants learners to hold.",
          "v0279-what-is-llm-q2-inner-awareness": "Not quite. That gives the model too much mind. Fluent behavior can happen without awareness.",
          "v0279-what-is-llm-q2-hidden-source": "Close, but this describes search or retrieval better than a plain LLM response. A fluent answer is not the same as cited evidence.",
          "v0279-what-is-llm-q2-prompt-learning": "That would require training. A normal prompt can shape temporary context without durably updating weights."
        }
      }
    ]
  },
  "where-llms-fit": {
    "questions": [
      {
        "id": "v0279-where-llms-fit-q1",
        "question": "A campus tool summarizes text with an LLM, while another creates images by denoising a noisy pattern. What does that show?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q1-correct",
            "text": "Generative AI is a family; LLMs and diffusion models are different branches."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-all-llms",
            "text": "All generative AI tools are LLMs because ChatGPT is generative AI."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-text-only-ai",
            "text": "The image tool is not AI unless it generates language tokens."
          },
          {
            "choiceId": "v0279-where-llms-fit-q1-ai-ml-same",
            "text": "AI and machine learning are the same label, so the branches do not matter."
          }
        ],
        "answer": "Generative AI is a family; LLMs and diffusion models are different branches.",
        "correctChoiceId": "v0279-where-llms-fit-q1-correct",
        "explain": "Good distinction. Generative AI is a family, and different branches can use different mechanisms.",
        "feedback": {
          "v0279-where-llms-fit-q1-correct": "Good distinction. Generative AI is a family, and different branches can use different mechanisms.",
          "v0279-where-llms-fit-q1-all-llms": "Not quite. An LLM is one kind of generative AI, not the whole category.",
          "v0279-where-llms-fit-q1-text-only-ai": "Close, but image models can be AI without using the LLM text-token loop.",
          "v0279-where-llms-fit-q1-ai-ml-same": "This choice collapses useful categories. Machine learning is a major branch inside the broader AI field."
        }
      },
      {
        "id": "v0279-where-llms-fit-q2",
        "question": "When people say an LLM sits inside the broader AI family, which category map is most useful?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q2-correct",
            "text": "AI is broad; machine learning learns from data; deep learning uses layers; generative AI creates outputs; LLMs focus on language/code."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-all-ai-llm",
            "text": "AI means LLM; machine learning, deep learning, and generative AI are just extra names."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-rules-learned-same",
            "text": "Rule-based AI, machine learning, and LLMs all work by following the same written rules."
          },
          {
            "choiceId": "v0279-where-llms-fit-q2-diffusion-same-loop",
            "text": "Diffusion models, LLMs, and search engines all use the same language-token loop."
          }
        ],
        "answer": "AI is broad; machine learning learns from data; deep learning uses layers; generative AI creates outputs; LLMs focus on language/code.",
        "correctChoiceId": "v0279-where-llms-fit-q2-correct",
        "explain": "Insight strengthened. The map keeps overlapping terms useful without making them interchangeable.",
        "feedback": {
          "v0279-where-llms-fit-q2-correct": "Insight strengthened. The map keeps overlapping terms useful without making them interchangeable.",
          "v0279-where-llms-fit-q2-all-ai-llm": "Not quite. LLMs are an important branch, not the root of the AI tree.",
          "v0279-where-llms-fit-q2-rules-learned-same": "Close, but rule-based systems rely on explicit rules while learned models use patterns shaped from data.",
          "v0279-where-llms-fit-q2-diffusion-same-loop": "This choice reveals a common mix-up. Diffusion often denoises patterns; LLM text generation usually appends response tokens."
        }
      },
      {
        "id": "v0279-where-llms-fit-q3",
        "question": "A chatbot product includes an LLM, a search tool, safety filters, and a user interface. What is the LLM?",
        "choices": [
          {
            "choiceId": "v0279-where-llms-fit-q3-correct",
            "text": "The language-generating model inside the larger product."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-whole-app",
            "text": "The whole app, including every tool and button."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-safety-policy",
            "text": "The safety policy that blocks some outputs."
          },
          {
            "choiceId": "v0279-where-llms-fit-q3-search-index",
            "text": "The database or search index the app may call."
          }
        ],
        "answer": "The language-generating model inside the larger product.",
        "correctChoiceId": "v0279-where-llms-fit-q3-correct",
        "explain": "Good distinction. A product may wrap an LLM with tools, policies, and interface pieces.",
        "feedback": {
          "v0279-where-llms-fit-q3-correct": "Good distinction. A product may wrap an LLM with tools, policies, and interface pieces.",
          "v0279-where-llms-fit-q3-whole-app": "Not quite. The product can include an LLM, but the LLM is not every surrounding tool and screen.",
          "v0279-where-llms-fit-q3-safety-policy": "Close, but a safety policy shapes behavior around the model; it is not the language model itself.",
          "v0279-where-llms-fit-q3-search-index": "This describes a retrieval or search component. The LLM generates language from context and learned weights."
        }
      }
    ]
  },
  "history": {
    "questions": [
      {
        "id": "v0279-history-q1",
        "question": "If a system solves a task only by following hand-written if-then rules, how is it different from an LLM?",
        "choices": [
          {
            "choiceId": "v0279-history-q1-correct",
            "text": "The rule-based system applies explicit rules; an LLM’s fluency mostly comes from learned weights shaped by examples."
          },
          {
            "choiceId": "v0279-history-q1-loss-every-task",
            "text": "The rule-based system measures loss and updates weights after every task."
          },
          {
            "choiceId": "v0279-history-q1-conscious-llm",
            "text": "The LLM has conscious reasoning, while the rule-based system has none."
          },
          {
            "choiceId": "v0279-history-q1-all-rules",
            "text": "There is no difference; both systems are just written rulebooks."
          }
        ],
        "answer": "The rule-based system applies explicit rules; an LLM’s fluency mostly comes from learned weights shaped by examples.",
        "correctChoiceId": "v0279-history-q1-correct",
        "explain": "Good distinction. LLMs mostly belong to the learned-patterns tradition, even when products around them use rules.",
        "feedback": {
          "v0279-history-q1-correct": "Good distinction. LLMs mostly belong to the learned-patterns tradition, even when products around them use rules.",
          "v0279-history-q1-loss-every-task": "Not quite. Loss and weight updates belong to training learned models, not to a pure if-then rule system.",
          "v0279-history-q1-conscious-llm": "That gives the LLM too much mind. The key boundary here is learned weights versus explicit rules.",
          "v0279-history-q1-all-rules": "Close, but LLM behavior is not mainly written as explicit if-then rules; it is shaped by training."
        }
      },
      {
        "id": "v0279-history-q2",
        "question": "During deep-learning training, why does the system measure loss?",
        "choices": [
          {
            "choiceId": "v0279-history-q2-correct",
            "text": "Loss measures prediction error so an optimizer can adjust weights."
          },
          {
            "choiceId": "v0279-history-q2-moral-good",
            "text": "Loss tells the model whether a generated answer is morally good."
          },
          {
            "choiceId": "v0279-history-q2-confidence-score",
            "text": "Loss is the model’s confidence score for the next token during generation."
          },
          {
            "choiceId": "v0279-history-q2-final-answer",
            "text": "Loss writes the final answer after the model has finished thinking."
          }
        ],
        "answer": "Loss measures prediction error so an optimizer can adjust weights.",
        "correctChoiceId": "v0279-history-q2-correct",
        "explain": "Insight strengthened. Loss is the numerical training signal, not a feeling or truth meter.",
        "feedback": {
          "v0279-history-q2-correct": "Insight strengthened. Loss is the numerical training signal, not a feeling or truth meter.",
          "v0279-history-q2-moral-good": "Not quite. Loss is a numerical error signal; alignment and policy questions need additional methods.",
          "v0279-history-q2-confidence-score": "Close, but confidence or probability shapes generation. Loss measures training error so weights can be adjusted.",
          "v0279-history-q2-final-answer": "Not quite. Loss is used during training; it is not the model writing a response."
        }
      },
      {
        "id": "v0279-history-q3",
        "question": "A university AI app uses an LLM plus policy filters, retrieval, and hand-written rules. What should a model-literate user conclude?",
        "choices": [
          {
            "choiceId": "v0279-history-q3-correct",
            "text": "Modern AI products can combine learned models, rules, tools, and policies; the LLM inside is still a learned-pattern model."
          },
          {
            "choiceId": "v0279-history-q3-no-learning-if-rules",
            "text": "Any rule in the app means the LLM is no longer trained from data."
          },
          {
            "choiceId": "v0279-history-q3-conscious-product",
            "text": "Any fluent answer means the app is consciously reasoning."
          },
          {
            "choiceId": "v0279-history-q3-permanent-finetune",
            "text": "Retrieval or filters permanently fine-tune the model on every use."
          }
        ],
        "answer": "Modern AI products can combine learned models, rules, tools, and policies; the LLM inside is still a learned-pattern model.",
        "correctChoiceId": "v0279-history-q3-correct",
        "explain": "Good distinction. The product can be hybrid even when the LLM itself is learned from data.",
        "feedback": {
          "v0279-history-q3-correct": "Good distinction. The product can be hybrid even when the LLM itself is learned from data.",
          "v0279-history-q3-no-learning-if-rules": "Not quite. Rules can wrap or guide a learned model without erasing the learned weights inside it.",
          "v0279-history-q3-conscious-product": "That gives the model too much mind. The app can combine tools and still lack conscious understanding.",
          "v0279-history-q3-permanent-finetune": "Close, but retrieval and filters can shape the current response without durably changing model weights."
        }
      }
    ]
  },
  "training": {
    "questions": [
      {
        "id": "v0279-training-q1",
        "question": "During training, the model predicts a target token and gets it wrong. What makes that moment learning rather than ordinary inference?",
        "choices": [
          {
            "choiceId": "v0279-training-q1-correct",
            "text": "The training process uses the loss signal to update weights."
          },
          {
            "choiceId": "v0279-training-q1-append-response",
            "text": "The model appends the mistaken token to a normal live response."
          },
          {
            "choiceId": "v0279-training-q1-durable-memory",
            "text": "The prompt becomes durable memory stored inside the model’s weights."
          },
          {
            "choiceId": "v0279-training-q1-likelihood-truth",
            "text": "The model treats the most likely answer as automatically true."
          }
        ],
        "answer": "The training process uses the loss signal to update weights.",
        "correctChoiceId": "v0279-training-q1-correct",
        "explain": "Good distinction. The durable weight update is what makes this training.",
        "feedback": {
          "v0279-training-q1-correct": "Good distinction. The durable weight update is what makes this training.",
          "v0279-training-q1-append-response": "Not quite. Appending a response token is inference behavior; training uses loss to change weights.",
          "v0279-training-q1-durable-memory": "This choice reveals a common mix-up. Context can shape the current chat without becoming a weight update.",
          "v0279-training-q1-likelihood-truth": "Not quite. Likelihood is not truth, and this training moment matters because loss can drive a weight update."
        }
      },
      {
        "id": "v0279-training-q2",
        "question": "A student asks a chatbot one question during ordinary use. Which statement is usually true?",
        "choices": [
          {
            "choiceId": "v0279-training-q2-correct",
            "text": "The model uses fixed weights and temporary context; the chat usually does not rewrite the weights."
          },
          {
            "choiceId": "v0279-training-q2-permanent-update",
            "text": "The chat permanently updates the base model’s weights."
          },
          {
            "choiceId": "v0279-training-q2-durable-memory",
            "text": "The model stores the prompt as durable memory inside its weights."
          },
          {
            "choiceId": "v0279-training-q2-optimizer-after-response",
            "text": "The optimizer trains the model after every response."
          }
        ],
        "answer": "The model uses fixed weights and temporary context; the chat usually does not rewrite the weights.",
        "correctChoiceId": "v0279-training-q2-correct",
        "explain": "Insight strengthened. Normal chat inference can use context, but it usually does not rewrite weights.",
        "feedback": {
          "v0279-training-q2-correct": "Insight strengthened. Normal chat inference can use context, but it usually does not rewrite weights.",
          "v0279-training-q2-permanent-update": "Not quite. That would require a training process, not ordinary inference.",
          "v0279-training-q2-durable-memory": "This choice reveals a common mix-up. Context can shape the current chat without becoming a weight update.",
          "v0279-training-q2-optimizer-after-response": "Close, but optimizers update weights during training, not after every normal response."
        }
      },
      {
        "id": "v0279-training-q3",
        "question": "Why can training change how the model behaves tomorrow, while inference usually cannot?",
        "choices": [
          {
            "choiceId": "v0279-training-q3-correct",
            "text": "Training changes parameters that future runs reuse; inference uses temporary computations for the current run."
          },
          {
            "choiceId": "v0279-training-q3-optimizer-inference",
            "text": "Inference is where the optimizer changes weights for future runs."
          },
          {
            "choiceId": "v0279-training-q3-prompt-only",
            "text": "Training only changes the visible prompt text for one response."
          },
          {
            "choiceId": "v0279-training-q3-truth-guarantee",
            "text": "Training guarantees that every future answer will be true."
          }
        ],
        "answer": "Training changes parameters that future runs reuse; inference uses temporary computations for the current run.",
        "correctChoiceId": "v0279-training-q3-correct",
        "explain": "Good distinction. Durable parameters carry forward; inference-time states usually do not.",
        "feedback": {
          "v0279-training-q3-correct": "Good distinction. Durable parameters carry forward; inference-time states usually do not.",
          "v0279-training-q3-optimizer-inference": "Not quite. Optimizer-driven weight updates belong to training, not ordinary inference.",
          "v0279-training-q3-prompt-only": "Close, but prompt changes are temporary input changes; training changes learned numbers.",
          "v0279-training-q3-truth-guarantee": "This choice overclaims. Training can improve behavior, but it does not guarantee truth."
        }
      },
      {
        "id": "v0279-training-q4",
        "question": "In a training loop, which sequence is the durable learning path?",
        "choices": [
          {
            "choiceId": "v0279-training-q4-correct",
            "text": "Example -> prediction -> loss -> weight update."
          },
          {
            "choiceId": "v0279-training-q4-generation-loop",
            "text": "Prompt -> response token -> append -> next response token."
          },
          {
            "choiceId": "v0279-training-q4-search-context",
            "text": "Search -> outside passage -> current context -> answer."
          },
          {
            "choiceId": "v0279-training-q4-user-correction",
            "text": "User correction -> better answer -> permanent learning inside the same chat."
          }
        ],
        "answer": "Example -> prediction -> loss -> weight update.",
        "correctChoiceId": "v0279-training-q4-correct",
        "explain": "Insight strengthened. That is the weight-changing path.",
        "feedback": {
          "v0279-training-q4-correct": "Insight strengthened. That is the weight-changing path.",
          "v0279-training-q4-generation-loop": "Close, but that sequence describes inference/generation, not training.",
          "v0279-training-q4-search-context": "That describes a search or retrieval step. It can add temporary context; it does not by itself update weights.",
          "v0279-training-q4-user-correction": "Not quite. A correction can steer the current conversation, but durable learning requires a training process."
        }
      }
    ]
  },
  "pretraining": {
    "questions": [
      {
        "id": "v0279-pretraining-q1",
        "question": "During pretraining, what signal teaches the model broad language patterns across many examples?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q1-correct",
            "text": "Repeated prediction error/loss from next-token targets changes weights over many training steps."
          },
          {
            "choiceId": "v0279-pretraining-q1-live-chat",
            "text": "A user conversation at deployment permanently rewrites the model."
          },
          {
            "choiceId": "v0279-pretraining-q1-written-rules",
            "text": "A human writes every rule the model will follow."
          },
          {
            "choiceId": "v0279-pretraining-q1-perfect-copy",
            "text": "The model stores a perfect copy of every source document."
          }
        ],
        "answer": "Repeated prediction error/loss from next-token targets changes weights over many training steps.",
        "correctChoiceId": "v0279-pretraining-q1-correct",
        "explain": "Good distinction. Pretraining scales the training loop across many examples.",
        "feedback": {
          "v0279-pretraining-q1-correct": "Good distinction. Pretraining scales the training loop across many examples.",
          "v0279-pretraining-q1-live-chat": "Not quite. Pretraining happens before normal use; an ordinary chat usually does not rewrite weights.",
          "v0279-pretraining-q1-written-rules": "Close, but pretraining is learned from examples, not a complete rulebook written by hand.",
          "v0279-pretraining-q1-perfect-copy": "This choice reveals a common mix-up. Pretraining shapes weights; it is not perfect document storage."
        }
      },
      {
        "id": "v0279-pretraining-q2",
        "question": "Why can pretraining create broad capability without making the model a perfect library of its sources?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q2-correct",
            "text": "It shapes statistical patterns in weights; it does not create a searchable copy of every source."
          },
          {
            "choiceId": "v0279-pretraining-q2-private-files",
            "text": "It gives the model direct access to every private file on demand."
          },
          {
            "choiceId": "v0279-pretraining-q2-search-context",
            "text": "It inserts the original source into every future prompt context."
          },
          {
            "choiceId": "v0279-pretraining-q2-after-user-prompt",
            "text": "It happens only after a user asks a specific question."
          }
        ],
        "answer": "It shapes statistical patterns in weights; it does not create a searchable copy of every source.",
        "correctChoiceId": "v0279-pretraining-q2-correct",
        "explain": "Good distinction. Pretraining can shape broad ability without turning the model into a perfect source library.",
        "feedback": {
          "v0279-pretraining-q2-correct": "Good distinction. Pretraining can shape broad ability without turning the model into a perfect source library.",
          "v0279-pretraining-q2-private-files": "Not quite. Training data exposure is not the same as access to every private file.",
          "v0279-pretraining-q2-search-context": "Close, but adding source text to context is different from pretraining. Pretraining changes weights before use.",
          "v0279-pretraining-q2-after-user-prompt": "Pretraining happens before deployment. The user prompt later uses the pretrained weights."
        }
      },
      {
        "id": "v0279-pretraining-q3",
        "question": "If pretraining examples include many styles and task shapes, what can change inside the model?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q3-correct",
            "text": "Weights can shift so future prompts activate more useful language/code patterns."
          },
          {
            "choiceId": "v0279-pretraining-q3-current-context",
            "text": "The model’s current chat context becomes permanently larger."
          },
          {
            "choiceId": "v0279-pretraining-q3-interface",
            "text": "Only the app’s buttons, labels, or interface change."
          },
          {
            "choiceId": "v0279-pretraining-q3-safety-policy",
            "text": "Only a safety policy is added around the model."
          }
        ],
        "answer": "Weights can shift so future prompts activate more useful language/code patterns.",
        "correctChoiceId": "v0279-pretraining-q3-correct",
        "explain": "Good distinction. Pretraining changes reusable model structure before later prompts arrive.",
        "feedback": {
          "v0279-pretraining-q3-correct": "Good distinction. Pretraining changes reusable model structure before later prompts arrive.",
          "v0279-pretraining-q3-current-context": "Not quite. Context is temporary input; pretraining changes reusable weights before later prompts arrive.",
          "v0279-pretraining-q3-interface": "This describes product UI changes, not the model’s learned parameters.",
          "v0279-pretraining-q3-safety-policy": "Close, but a policy can shape a product around the model; pretraining changes the model’s reusable weights."
        }
      },
      {
        "id": "v0279-pretraining-q4",
        "question": "A base model produces fact-like text about public topics. What is the model-literate explanation?",
        "choices": [
          {
            "choiceId": "v0279-pretraining-q4-correct",
            "text": "Pretraining shaped weights with patterns from data, so the model may generate fact-like text without retrieving the original page."
          },
          {
            "choiceId": "v0279-pretraining-q4-web-every-time",
            "text": "It must be browsing the web by itself for every answer."
          },
          {
            "choiceId": "v0279-pretraining-q4-conscious-memory",
            "text": "It must consciously remember reading those pages."
          },
          {
            "choiceId": "v0279-pretraining-q4-finetuning-alone",
            "text": "Fine-tuning alone explains all broad model knowledge."
          }
        ],
        "answer": "Pretraining shaped weights with patterns from data, so the model may generate fact-like text without retrieving the original page.",
        "correctChoiceId": "v0279-pretraining-q4-correct",
        "explain": "Insight strengthened. Source-like output can come from pretrained patterns, but it is not the same as cited evidence.",
        "feedback": {
          "v0279-pretraining-q4-correct": "Insight strengthened. Source-like output can come from pretrained patterns, but it is not the same as cited evidence.",
          "v0279-pretraining-q4-web-every-time": "Not quite. Some systems browse or retrieve, but a base model can also generate fact-like text from pretrained weights.",
          "v0279-pretraining-q4-conscious-memory": "That gives the model too much mind. It has learned weights, not conscious recollection.",
          "v0279-pretraining-q4-finetuning-alone": "Close, but fine-tuning is targeted shaping after broad pretraining; it does not usually explain the whole foundation."
        }
      }
    ]
  },
  "overfitting-generalization": {
    "questions": [
      {
        "id": "v0279-overfitting-generalization-q1",
        "question": "A model gets every training example right but fails on new validation examples. What problem is showing up?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q1-correct",
            "text": "Overfitting: the model fit training examples too narrowly instead of learning patterns that generalize."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-generalization",
            "text": "Generalization: the model is working well on unseen cases."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-better-training",
            "text": "Better training: the model has clearly learned the general rule."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q1-inference",
            "text": "Inference: the model is simply generating one token at a time."
          }
        ],
        "answer": "Overfitting: the model fit training examples too narrowly instead of learning patterns that generalize.",
        "correctChoiceId": "v0279-overfitting-generalization-q1-correct",
        "explain": "Good diagnosis. The held-out examples reveal whether the pattern transfers.",
        "feedback": {
          "v0279-overfitting-generalization-q1-correct": "Good diagnosis. The held-out examples reveal whether the pattern transfers.",
          "v0279-overfitting-generalization-q1-generalization": "Not quite. Generalization means good performance on new examples; this scenario shows the opposite.",
          "v0279-overfitting-generalization-q1-better-training": "Not quite. If it fails on new validation examples, high training performance is not enough evidence of generalization.",
          "v0279-overfitting-generalization-q1-inference": "Close, but inference is normal model use; overfitting is a training/evaluation failure mode."
        }
      },
      {
        "id": "v0279-overfitting-generalization-q2",
        "question": "Why do model builders test on held-out validation data instead of only training examples?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q2-correct",
            "text": "Held-out data checks whether learned patterns work on examples the model did not train on."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-extra-training",
            "text": "Validation data is just extra training data used to lower loss."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-training-proves-all",
            "text": "Training examples alone prove the model will work everywhere."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q2-loss-truth",
            "text": "A lower loss always proves every future answer is true."
          }
        ],
        "answer": "Held-out data checks whether learned patterns work on examples the model did not train on.",
        "correctChoiceId": "v0279-overfitting-generalization-q2-correct",
        "explain": "Insight strengthened. Validation is about transfer, not memorized training performance.",
        "feedback": {
          "v0279-overfitting-generalization-q2-correct": "Insight strengthened. Validation is about transfer, not memorized training performance.",
          "v0279-overfitting-generalization-q2-extra-training": "Not quite. Validation data is held out to check transfer; it should not simply be another set of examples used to fit weights.",
          "v0279-overfitting-generalization-q2-training-proves-all": "This choice reveals the exact overfitting risk. Seen examples are not enough evidence.",
          "v0279-overfitting-generalization-q2-loss-truth": "Close, but lower loss is not a truth guarantee, especially outside the tested examples."
        }
      },
      {
        "id": "v0279-overfitting-generalization-q3",
        "question": "A model trained heavily on one narrow answer template works on that template but struggles with varied new prompts. What should a model-literate learner suspect?",
        "choices": [
          {
            "choiceId": "v0279-overfitting-generalization-q3-correct",
            "text": "It may have fit the narrow examples too closely instead of learning a pattern that generalizes."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-prompt-rewrite",
            "text": "The prompts permanently rewrote the model during inference."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-conscious-choice",
            "text": "The model is definitely conscious but choosing not to answer."
          },
          {
            "choiceId": "v0279-overfitting-generalization-q3-rules-always-better",
            "text": "Rule-based AI is always better than learned models."
          }
        ],
        "answer": "It may have fit the narrow examples too closely instead of learning a pattern that generalizes.",
        "correctChoiceId": "v0279-overfitting-generalization-q3-correct",
        "explain": "Good distinction. Targeted training can help, but narrow training can also make behavior brittle.",
        "feedback": {
          "v0279-overfitting-generalization-q3-correct": "Good distinction. Targeted training can help, but narrow training can also make behavior brittle.",
          "v0279-overfitting-generalization-q3-prompt-rewrite": "Not quite. The issue is training behavior, not prompts rewriting weights during inference.",
          "v0279-overfitting-generalization-q3-conscious-choice": "That gives the model too much mind. The issue is brittle transfer, not intention.",
          "v0279-overfitting-generalization-q3-rules-always-better": "This overgeneralizes. The issue is narrow training behavior, not proof that rules always beat learned models."
        }
      }
    ]
  }
} as const

export type CheckpointBankLessonId = keyof typeof FIRST_SIX_CHECKPOINT_BANK_V0279

export function hasV0279CheckpointBank(lessonId: string): lessonId is CheckpointBankLessonId {
  return Object.prototype.hasOwnProperty.call(FIRST_SIX_CHECKPOINT_BANK_V0279, lessonId)
}
