export type ExerciseInputType =
  | 'tap-choice'
  | 'tap-multiple'
  | 'drag-order'
  | 'drag-match'
  | 'sort-buckets'
  | 'connect-nodes'
  | 'toggle-state'
  | 'type-reflection'
  | 'label-tokens'
  | 'next-token-pick'

export type ExerciseItem = {
  id: string
  label: string
  detail?: string
  bucket?: string
  group?: string
  correct?: boolean
  feedback?: string
  matchId?: string
}

export type Exercise = {
  id: string
  title: string
  concept: string
  prompt: string
  goal: string
  actionVerb: 'Tap' | 'Touch' | 'Drag' | 'Sort' | 'Connect' | 'Choose' | 'Label' | 'Type' | 'Toggle' | 'Order'
  actionInstruction: string
  inputType: ExerciseInputType
  items: ExerciseItem[]
  buckets?: string[]
  context?: string
  sequence?: string[]
  windowSize?: number
  targetId?: string
  correctAnswer?: string | string[]
  correctActions?: Record<string, string> | string[]
  incorrectActions?: Record<string, string>
  feedbackCorrect: string
  feedbackIncorrect: string
  insight: string
  glossaryTerms: string[]
  brainMetaphor?: string
  brainLimit?: string
  completionKey: string
}

import { attentionExample, canonicalPromptResponse } from './canonicalExamples'

export const exercises: Exercise[] = [
  {
    id: 'prompt-or-response-label',
    title: 'Prompt or Response?',
    concept: 'Prompt tokens versus generated response tokens',
    prompt: `User prompt: ${canonicalPromptResponse.userPrompt} Response so far: ${canonicalPromptResponse.responseSoFar}. Next token: ${canonicalPromptResponse.chosenNextToken}.`,
    goal: 'Practice telling the complete user prompt apart from generated response tokens.',
    actionVerb: 'Label',
    actionInstruction: 'Label the user request as Prompt and the generated sentence pieces as Response.',
    inputType: 'label-tokens',
    buckets: ['Prompt', 'Response'],
    items: [
      { id: 'user-prompt', label: 'User prompt: pet-conflict sentence request', bucket: 'Prompt', feedback: 'The user prompt is a complete request supplied before generation.' },
      ...canonicalPromptResponse.responseSoFarTokens.map((token, index) => ({ id: `response-${index}`, label: token, bucket: 'Response' } as ExerciseItem)),
      { id: 'response-floor', label: 'floor', bucket: 'Response', feedback: 'floor is one generated response token, then it is appended to the context.' }
    ],
    correctActions: {
      'user-prompt': 'Prompt',
      ...Object.fromEntries(canonicalPromptResponse.responseSoFarTokens.map((_, index) => [`response-${index}`, 'Response'])),
      'response-floor': 'Response'
    },
    incorrectActions: {
      'user-prompt:Response': 'The user prompt is the complete request supplied by the user, not generated by the model.',
      'response-floor:Prompt': 'floor was generated by the model, then appended to the response-so-far.'
    },
    feedbackCorrect: 'Insight unlocked. The user prompt is given; the response sentence is generated one token at a time.',
    feedbackIncorrect: 'Not quite. The complete request is the prompt, while the pet-conflict sentence is generated response text.',
    insight: 'A response grows one generated token at a time.',
    glossaryTerms: ['prompt', 'response', 'generated token', 'context window', 'autoregression'],
    completionKey: 'exercise:prompt-or-response-label'
  },
  {
    id: 'pick-next-token',
    title: 'Pick the Next Token',
    concept: 'Next-token probabilities',
    prompt: `User prompt: ${canonicalPromptResponse.userPrompt}`,
    goal: 'Choose the strongest next token from the response-so-far.',
    actionVerb: 'Tap',
    actionInstruction: 'Tap the token the model should generate next.',
    inputType: 'next-token-pick',
    context: `Response so far: ${canonicalPromptResponse.responseSoFar}`,
    items: [
      { id: 'floor', label: 'floor', correct: true, detail: 'best fit' },
      { id: 'room', label: 'room', correct: true, detail: 'plausible, weaker' },
      { id: 'tiles', label: 'tiles', correct: true, detail: 'plausible, weaker' },
      { id: 'counter', label: 'counter', feedback: 'counter is a household object, but it is less natural after across the kitchen.' },
      { id: 'quantum', label: 'quantum', feedback: 'quantum is possible in the vocabulary, but unlikely in this local context.' },
      { id: 'elephant', label: 'elephant', feedback: 'elephant is possible in the vocabulary, but unlikely in this pet-conflict sentence.' }
    ],
    correctAnswer: [...canonicalPromptResponse.plausibleNextTokens],
    feedbackCorrect: 'Insight unlocked. floor fits the response-so-far and the user request for a pet-conflict example.',
    feedbackIncorrect: 'Not quite. That token may exist in the vocabulary, but it is unlikely in this local context.',
    insight: 'The model chooses from probabilities, not certainty.',
    glossaryTerms: ['logits', 'softmax', 'sampling', 'next token'],
    completionKey: 'exercise:pick-next-token'
  },
  {
    id: 'durable-or-temporary',
    title: 'Durable or Temporary?',
    concept: 'Training versus inference-time steering',
    prompt: 'Some processes change model weights. Others only change what the model can see right now.',
    goal: 'Sort learning and steering processes by what they actually change.',
    actionVerb: 'Sort',
    actionInstruction: 'Sort each item into Durable weight change, Temporary current-run steering, or Retrieval, not learning.',
    inputType: 'sort-buckets',
    buckets: ['Durable weight change', 'Temporary current-run steering', 'Retrieval, not learning'],
    items: [
      { id: 'pretraining', label: 'pretraining', bucket: 'Durable weight change' },
      { id: 'fine-tuning', label: 'fine-tuning', bucket: 'Durable weight change' },
      { id: 'human-feedback', label: 'human feedback learning', bucket: 'Durable weight change' },
      { id: 'in-context-examples', label: 'in-context examples', bucket: 'Temporary current-run steering' },
      { id: 'system-prompt', label: 'system prompt', bucket: 'Temporary current-run steering' },
      { id: 'retrieved-pdf', label: 'retrieved PDF', bucket: 'Retrieval, not learning' },
      { id: 'normal-inference', label: 'normal inference', bucket: 'Temporary current-run steering' },
      { id: 'rag-document', label: 'RAG document', bucket: 'Retrieval, not learning' },
      { id: 'online-learning', label: 'online learning', bucket: 'Durable weight change' }
    ],
    feedbackCorrect: 'Good. You separated durable model changes from temporary context changes.',
    feedbackIncorrect: 'A durable process changes weights. Prompting, examples, and normal inference only steer the current run. Retrieval places material in context.',
    insight: 'Some processes change the model. Others only change what the model sees right now.',
    glossaryTerms: ['training', 'fine-tuning', 'inference', 'RAG', 'in-context learning'],
    completionKey: 'exercise:durable-or-temporary'
  },
  {
    id: 'attention-relevance',
    title: 'Attention Is Relevance',
    concept: 'Attention-like relevance between token positions',
    prompt: attentionExample.sentence,
    goal: 'Connect the pronoun to the token it most likely depends on.',
    actionVerb: 'Connect',
    actionInstruction: 'Connect it to the most likely referent.',
    inputType: 'connect-nodes',
    targetId: 'it',
    correctAnswer: 'cat',
    items: [
      { id: 'a-1', label: 'A' },
      { id: 'jealous', label: 'jealous' },
      { id: 'dog', label: 'dog', feedback: 'dog is possible in some sentences, but here cat is the more likely referent.' },
      { id: 'chased', label: 'chased' },
      { id: 'a-2', label: 'a' },
      { id: 'startled', label: 'startled' },
      { id: 'cat', label: 'cat', correct: true },
      { id: 'because', label: 'because' },
      { id: 'it', label: 'it' },
      { id: 'hissed', label: 'hissed' }
    ],
    feedbackCorrect: 'Good. In this sentence, it hissed most likely refers to the cat.',
    feedbackIncorrect: 'dog is possible in some sentences, but here cat is the more likely referent.',
    insight: 'Attention-like relevance helps token positions use context.',
    glossaryTerms: ['attention', 'context', 'hidden state'],
    brainMetaphor: 'Like focusing on the relevant word.',
    brainLimit: 'Attention is not awareness. It is learned relevance weighting.',
    completionKey: 'exercise:attention-relevance'
  },
  {
    id: 'context-window-fell-out',
    title: 'Context Window: What Fell Out?',
    concept: 'Temporary visible context',
    prompt: 'A context window can only hold the newest four cards.',
    goal: 'Identify which older information the model can no longer use after the window fills.',
    actionVerb: 'Tap',
    actionInstruction: 'Tap a card that fell out of the current context window.',
    inputType: 'tap-choice',
    sequence: ['System: be concise', 'User: explain LLMs', 'Example: pet-conflict sentence', 'Tone: academic', 'Distractor: jokes', 'Output: three bullets'],
    windowSize: 4,
    items: [
      { id: 'system', label: 'System: be concise', correct: true },
      { id: 'user', label: 'User: explain LLMs', correct: true },
      { id: 'tone', label: 'Tone: academic', feedback: 'Tone is still inside the last four cards, so it remains visible.' },
      { id: 'output', label: 'Output: three bullets', feedback: 'Output is the newest card, so it remains visible.' }
    ],
    correctAnswer: ['system', 'user'],
    feedbackCorrect: 'Good. Older cards fell out when newer cards entered the limited window.',
    feedbackIncorrect: 'That card is still in the current window. The oldest cards are no longer visible.',
    insight: 'The model can only use what fits in the current context window.',
    glossaryTerms: ['context window', 'prompt token', 'input context', 'memory'],
    completionKey: 'exercise:context-window-fell-out'
  },
  {
    id: 'training-nudge',
    title: 'Training Nudge',
    concept: 'Weight updates happen during training, not normal inference',
    prompt: 'Prediction: room. Actual next token: floor. Loss: high.',
    goal: 'Choose when Update weights belongs.',
    actionVerb: 'Toggle',
    actionInstruction: 'Toggle between Training and Inference, then check the state where Update weights is correct.',
    inputType: 'toggle-state',
    correctAnswer: 'training',
    items: [
      { id: 'training', label: 'Training', detail: 'Prediction error can update weights.', correct: true },
      { id: 'inference', label: 'Inference', detail: 'Fixed weights produce a response token.', feedback: 'Normal inference uses fixed weights and does not durably update the model.' }
    ],
    feedbackCorrect: 'Correct. Training uses prediction error to update weights.',
    feedbackIncorrect: 'Normal inference uses fixed weights and does not durably update the model.',
    insight: 'Prediction error can train the model only in a training process.',
    glossaryTerms: ['training', 'loss', 'weight', 'inference'],
    completionKey: 'exercise:training-nudge'
  },
  {
    id: 'softmax-funnel',
    title: 'Softmax Funnel',
    concept: 'Raw scores become probabilities',
    prompt: 'Raw scores: floor 8.1, room 5.8, quantum 0.3.',
    goal: 'Identify what softmax produces.',
    actionVerb: 'Choose',
    actionInstruction: 'Choose the output of softmax.',
    inputType: 'tap-choice',
    items: [
      { id: 'probability-distribution', label: 'A probability distribution', correct: true },
      { id: 'permanent-memory', label: 'A permanent memory', feedback: 'Softmax is part of decoding; it does not store memory.' },
      { id: 'full-sentence', label: 'A full sentence', feedback: 'Softmax prepares next-token probabilities, not a whole answer.' },
      { id: 'database-lookup', label: 'A database lookup', feedback: 'Softmax transforms scores; it is not retrieval.' }
    ],
    correctAnswer: 'probability-distribution',
    feedbackCorrect: 'Good. Softmax turns raw scores into probabilities that sum to one.',
    feedbackIncorrect: 'Softmax turns raw next-token scores into probabilities.',
    insight: 'Softmax turns raw next-token scores into probabilities.',
    glossaryTerms: ['logits', 'softmax', 'probability', 'sampling'],
    completionKey: 'exercise:softmax-funnel'
  },
  {
    id: 'mlp-feature-reshape',
    title: 'MLP Feature Reshape',
    concept: 'Context-shaped features',
    prompt: 'Token: cat',
    goal: 'See that the same token can carry different temporary features in different contexts.',
    actionVerb: 'Toggle',
    actionInstruction: 'Toggle to the command-line context where cat no longer means the animal.',
    inputType: 'toggle-state',
    correctAnswer: 'command-context',
    items: [
      { id: 'animal-context', label: 'A startled cat hissed', detail: 'animal, noun, acting thing' },
      { id: 'command-context', label: 'The cat command printed the file', detail: 'tool name, noun, file command', correct: true }
    ],
    feedbackCorrect: 'Good. The same token can carry different contextual features after layers update it.',
    feedbackIncorrect: 'In this context, cat still behaves like the animal meaning. Toggle to the command context to see the feature shift.',
    insight: 'The token hidden state changes with context.',
    glossaryTerms: ['MLP', 'hidden state', 'feature', 'context'],
    completionKey: 'exercise:mlp-feature-reshape'
  },
  {
    id: 'open-book-or-learned',
    title: 'Open Book or Learned?',
    concept: 'Weights, retrieved context, and temporary instructions',
    prompt: 'RAG can feel like learning, but it usually places source material into context.',
    goal: 'Sort each item by whether it lives in weights, enters context, or is generated as response text.',
    actionVerb: 'Sort',
    actionInstruction: 'Sort each item into Learned in weights, Placed in context, or Generated response.',
    inputType: 'sort-buckets',
    buckets: ['Learned in weights', 'Placed in context', 'Generated response'],
    items: [
      { id: 'trained-documents', label: 'Pretraining on many documents', bucket: 'Learned in weights' },
      { id: 'fine-tuned-support', label: 'Fine-tuning a support assistant', bucket: 'Learned in weights' },
      { id: 'retrieved-pdf', label: 'Retrieved policy PDF', bucket: 'Placed in context' },
      { id: 'search-snippet', label: 'Search result snippet', bucket: 'Placed in context' },
      { id: 'system-instruction', label: 'System instruction', bucket: 'Placed in context' },
      { id: 'user-prompt', label: 'User prompt', bucket: 'Placed in context' },
      { id: 'answer-paragraph', label: 'Generated answer paragraph', bucket: 'Generated response' },
      { id: 'generated-citation', label: 'Generated citation', bucket: 'Generated response' }
    ],
    feedbackCorrect: 'Good. You separated learned weights from open-book context.',
    feedbackIncorrect: 'RAG places material into context. It is not the same as training weights, and the answer is still generated.',
    insight: 'RAG is like an open-book exam. The book enters context; it is not permanently inside the model.',
    glossaryTerms: ['RAG', 'retrieval', 'context window', 'grounding', 'weights'],
    completionKey: 'exercise:open-book-or-learned'
  },
  {
    id: 'brain-metaphor-boundary',
    title: 'Brain Metaphor Boundary',
    concept: 'Useful metaphor, visible limits',
    prompt: 'Which brain metaphors are helpful, and where do they break?',
    goal: 'Select at least one helpful comparison and at least one break point.',
    actionVerb: 'Tap',
    actionInstruction: 'Tap one helpful comparison and one break point.',
    inputType: 'tap-multiple',
    items: [
      { id: 'signals-combine', label: 'many small signals combine', group: 'helpful' },
      { id: 'practice-shapes', label: 'practice can shape future behavior', group: 'helpful' },
      { id: 'working-memory', label: 'working memory resembles current context', group: 'helpful' },
      { id: 'no-feelings', label: 'no feelings', group: 'break' },
      { id: 'no-lived-body', label: 'no lived body', group: 'break' },
      { id: 'no-consciousness', label: 'no consciousness', group: 'break' },
      { id: 'no-goals', label: 'no personal goals', group: 'break' }
    ],
    correctActions: ['helpful', 'break'],
    feedbackCorrect: 'Good. You used the metaphor and kept its boundary visible.',
    feedbackIncorrect: 'Select both sides: one helpful comparison and one break point.',
    insight: 'Brain metaphors help only when their limits are visible.',
    glossaryTerms: ['neural network', 'attention', 'hidden state', 'training'],
    completionKey: 'exercise:brain-metaphor-boundary'
  }
]

export const exerciseById = Object.fromEntries(exercises.map((exercise) => [exercise.id, exercise])) as Record<string, Exercise>

export const lessonExerciseIds: Record<string, string> = {
  'what-is-llm': 'pick-next-token',
  history: 'durable-or-temporary',
  training: 'training-nudge',
  pretraining: 'training-nudge',
  'overfitting-generalization': 'durable-or-temporary',
  'fine-tuning': 'durable-or-temporary',
  alignment: 'durable-or-temporary',
  inference: 'training-nudge',
  tokens: 'prompt-or-response-label',
  'token-ids': 'prompt-or-response-label',
  embeddings: 'prompt-or-response-label',
  attention: 'attention-relevance',
  mlp: 'mlp-feature-reshape',
  'hidden-states': 'mlp-feature-reshape',
  logits: 'softmax-funnel',
  softmax: 'softmax-funnel',
  sampling: 'pick-next-token',
  autoregression: 'prompt-or-response-label',
  'context-window': 'context-window-fell-out',
  'rag-retrieval': 'open-book-or-learned',
  'brain-metaphor': 'brain-metaphor-boundary',
  'risk-myth': 'open-book-or-learned'
}

export function emptyExerciseProgress() {
  return {
    completed: [] as string[],
    attempts: {} as Record<string, number>,
    lastAnswers: {} as Record<string, unknown>,
    insights: [] as string[]
  }
}
